package com.wg.authority.user.entity;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_admin_role_relation
 */
public class UmsAdminRoleRelation {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_role_relation.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_role_relation.admin_id")
    private Long adminId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_role_relation.role_id")
    private Long roleId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_role_relation.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_role_relation.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_role_relation.admin_id")
    public Long getAdminId() {
        return adminId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_role_relation.admin_id")
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_role_relation.role_id")
    public Long getRoleId() {
        return roleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_role_relation.role_id")
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}