package com.wg.authority.user.entity;

import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_admin_login_log
 */
public class UmsAdminLoginLog {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.admin_id")
    private Long adminId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.create_time")
    private Date createTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.ip")
    private String ip;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.address")
    private String address;

    /**
     * Database Column Remarks:
     *   浏览器登录类型
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.user_agent")
    private String userAgent;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.admin_id")
    public Long getAdminId() {
        return adminId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.admin_id")
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.ip")
    public String getIp() {
        return ip;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.ip")
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.address")
    public String getAddress() {
        return address;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.address")
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.user_agent")
    public String getUserAgent() {
        return userAgent;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_admin_login_log.user_agent")
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }
}