package com.wg.authority.user.entity;

import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_menu
 */
public class UmsMenu {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   父级ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.parent_id")
    private Long parentId;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.create_time")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   菜单名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.title")
    private String title;

    /**
     * Database Column Remarks:
     *   菜单级数
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.level")
    private Integer level;

    /**
     * Database Column Remarks:
     *   菜单排序
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.sort")
    private Integer sort;

    /**
     * Database Column Remarks:
     *   前端名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.name")
    private String name;

    /**
     * Database Column Remarks:
     *   前端图标
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.icon")
    private String icon;

    /**
     * Database Column Remarks:
     *   前端隐藏
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.hidden")
    private Integer hidden;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.parent_id")
    public Long getParentId() {
        return parentId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.parent_id")
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.title")
    public String getTitle() {
        return title;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.title")
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.level")
    public Integer getLevel() {
        return level;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.level")
    public void setLevel(Integer level) {
        this.level = level;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.sort")
    public Integer getSort() {
        return sort;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.sort")
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.name")
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.icon")
    public String getIcon() {
        return icon;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.icon")
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.hidden")
    public Integer getHidden() {
        return hidden;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_menu.hidden")
    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }
}