package com.wg.authority.user.entity;

import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_role
 */
public class UmsRole {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.name")
    private String name;

    /**
     * Database Column Remarks:
     *   描述
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.description")
    private String description;

    /**
     * Database Column Remarks:
     *   后台用户数量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.admin_count")
    private Integer adminCount;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.create_time")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   启用状态：0->禁用；1->启用
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.status")
    private Integer status;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.sort")
    private Integer sort;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.name")
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.description")
    public String getDescription() {
        return description;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.description")
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.admin_count")
    public Integer getAdminCount() {
        return adminCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.admin_count")
    public void setAdminCount(Integer adminCount) {
        this.adminCount = adminCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.status")
    public Integer getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.status")
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.sort")
    public Integer getSort() {
        return sort;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role.sort")
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}