package com.wg.authority.user.entity;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_role_resource_relation
 */
public class UmsRoleResourceRelation {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role_resource_relation.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   角色ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role_resource_relation.role_id")
    private Long roleId;

    /**
     * Database Column Remarks:
     *   资源ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role_resource_relation.resource_id")
    private Long resourceId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role_resource_relation.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role_resource_relation.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role_resource_relation.role_id")
    public Long getRoleId() {
        return roleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role_resource_relation.role_id")
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role_resource_relation.resource_id")
    public Long getResourceId() {
        return resourceId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ums_role_resource_relation.resource_id")
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }
}