package com.wg.authority.generate.entity;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role_data_perm
 */
public class SysRoleDataPerm {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_role_data_perm.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   角色ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_role_data_perm.role_id")
    private Long roleId;

    /**
     * Database Column Remarks:
     *   权限ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_role_data_perm.perm_id")
    private Long permId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_role_data_perm.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_role_data_perm.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_role_data_perm.role_id")
    public Long getRoleId() {
        return roleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_role_data_perm.role_id")
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_role_data_perm.perm_id")
    public Long getPermId() {
        return permId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_role_data_perm.perm_id")
    public void setPermId(Long permId) {
        this.permId = permId;
    }
}